config/routes.rb
Rails.application.routes.draw do
  resources :products

  get '/report/', to: 'products#report'
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :sku, type: String
  field :description, type: String
  field :quantity, type: Integer
  field :price, type: Float
  field :bar_code, type: String

  validates_presence_of :name, :sku
  validates_length_of :bar_code, in: 8..13, allow_blank: true
  validates_numericality_of :price, only_float: true, allow_nil: true, greater_than: 0.0
  validates_format_of :sku, with: /\A[A-Za-z0-9\-]+\Z/
  validates_format_of :bar_code, allow_blank: true, with: /\A[0-9]+\Z/

  after_save :save_elastic_search, :to_redis
  after_destroy :delete_elestic_search, :del_redis_key

  def to_redis
    $redis.set(Product.redis_key(id), JSON(to_hash))
  end

  def self.from_redis(id)
    product_json = $redis.get(redis_key(id))

    Product.new.from_json(product_json) unless product_json.nil?
  end

  def to_hash
    {
      id: id.to_s,
      name: name,
      sku: sku,
      description: description,
      quantity: quantity,
      price: price,
      bar_code: bar_code,
      created_at: created_at,
      updated_at: updated_at
    }
  end

  def self.search(search)
    $es_repository.search(
      query: {
        query_string: {
          query: "*#{search}*", fields: [:name, :sku, :description]
        }
      }
    )
  end

  private

  def self.redis_key(id)
    "product:id_#{id}"
  end

  def del_redis_key
    $redis.del(Product.redis_key(id))
  end

  def save_elastic_search
    $es_repository.save self
  end

  def delete_elestic_search
    $es_repository.delete self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit]
  before_action :find_product, only: [:update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = if params[:search].present?
                  Product.search(params[:search])
                else
                  Product.all
                end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /report
  def report
    ProductsWorker.perform_async

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'O relatório será gerado e enviado por e-mail!' }
    end
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end

  def set_product
    @product = Product.from_redis(params[:id])

    if @product.nil?
      @product = Product.find(params[:id])
      @product.to_redis
    end
  end

  def product_params
    params.require(:product).permit(:name, :sku, :description, :quantity, :price, :bar_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductsRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product, url: url, method: method) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sku %><br>
    <%= f.text_area :sku %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :bar_code %><br>
    <%= f.text_field :bar_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', method: :put, url: product_path(@product.id) %>
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<h2>Search</h2>

<%= form_tag(products_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search..." %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

<h2>Report</h2>
<%= link_to 'Products Report', report_path %>

<h2>Listing Products</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sku</th>
      <th>Description</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Bar Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.sku %></td>
        <td><%= product.description %></td>
        <td><%= product.quantity %></td>
        <td><%= product.price %></td>
        <td><%= product.bar_code %></td>
        <td><%= link_to 'Show', product_path(product.id) %></td>
        <td><%= link_to 'Edit', edit_product_path(product.id) %></td>
        <td><%= link_to 'Destroy', product_path(product.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', method: :post, url: products_path %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Bar Code:</strong>
  <%= @product.bar_code %>
</p>

<%= link_to 'Edit', edit_product_path(@product.id) %> |
<%= link_to 'Back', products_path %>